import RellichKondrachov.Analysis.Calculus.ContDiff.Support
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.H1
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.H2
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.Approximation
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.ArzelaAscoli
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.Compactness
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.FrechetKolmogorov
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.Kernels
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.Smoothing
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.Transfer
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.TranslationIntegral
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2CompactnessCriterion
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.Rellich
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.SupportedH1
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.Translation
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.TranslationEstimate
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.TranslationEstimateH1
import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.TranslationEstimateL2
import RellichKondrachov.Geometry.Manifold.Riemannian.ChartLocalLipschitz
import RellichKondrachov.Geometry.Manifold.Riemannian.ChartLocalLipschitzForward
import RellichKondrachov.Geometry.Manifold.Riemannian.VolumeMeasure
import RellichKondrachov.Geometry.Manifold.Riemannian.VolumeMeasure.Finiteness
import RellichKondrachov.Geometry.Manifold.Sobolev.ChartData
import RellichKondrachov.Geometry.Manifold.Sobolev.ChartDataRiemannian
import RellichKondrachov.Geometry.Manifold.Sobolev.ChartMeasure
import RellichKondrachov.Geometry.Manifold.Sobolev.ChartMeasureLp
import RellichKondrachov.Geometry.Manifold.Sobolev.ChartMeasureRiemannian
import RellichKondrachov.Geometry.Manifold.Sobolev.ChartMeasureRiemannianVolume
import RellichKondrachov.Geometry.Manifold.Sobolev.EmbeddingL2
import RellichKondrachov.Geometry.Manifold.Sobolev.H1
import RellichKondrachov.Geometry.Manifold.Sobolev.H2
import RellichKondrachov.Geometry.Manifold.Sobolev.Localization
import RellichKondrachov.Geometry.Manifold.Sobolev.LocalizationH2
import RellichKondrachov.Geometry.Manifold.Sobolev.RellichKondrachov
import RellichKondrachov.Geometry.Manifold.Sobolev.RellichKondrachovRiemannian
import RellichKondrachov.Geometry.Manifold.Sobolev.RellichKondrachovRiemannian.Chartwise
import RellichKondrachov.Geometry.Manifold.Sobolev.RellichKondrachovRiemannian.Global
import RellichKondrachov.Geometry.Manifold.Sobolev.RellichKondrachovRiemannian.Transport
import RellichKondrachov.MeasureTheory.Function.LpSpace.ChangeMeasureLeSmul
import RellichKondrachov.MeasureTheory.Function.LpSpace.ExtendByZeroRangeEquiv
import RellichKondrachov.MeasureTheory.Function.LpSpace.Restrict
import RellichKondrachov.MeasureTheory.Measure.HausdorffVolume

/-
Copyright (c) 2026 Adam Benenson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Benenson
-/

/-!
# Rellich–Kondrachov Compact Embedding Theorem

This is the root import file for the Rellich–Kondrachov compact embedding theorem.
-/
